# Generated by Django 2.0.5 on 2018-07-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
