# Generated by Django 2.0.5 on 2018-08-12 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20180812_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(through='posts.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
