# Generated by Django 2.0.5 on 2018-08-12 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20180812_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_like',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(through='posts.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
