# Generated by Django 2.0.5 on 2018-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20180812_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_like',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
