# Generated by Django 2.0.5 on 2018-07-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
