# Generated by Django 2.0.5 on 2018-07-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20180713_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
