# Generated by Django 2.0.5 on 2018-07-21 09:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180721_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='weight',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
