# Generated by Django 2.0.5 on 2018-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180721_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightlist',
            name='user_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
