# Generated by Django 2.0.5 on 2018-07-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_weightlist_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.WeightList'),
        ),
    ]
