# Generated by Django 2.0.5 on 2018-07-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofileinfo_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='weightlist',
            name='user',
        ),
    ]
