# Generated by Django 2.0.5 on 2018-07-21 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20180721_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightlist',
            old_name='user_weight',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='weightlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
