# Generated by Django 2.0.5 on 2018-07-21 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180721_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightlist',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='weight_history',
            field=models.ManyToManyField(blank=True, related_name='weight_list', to='accounts.WeightList'),
        ),
        migrations.AddField(
            model_name='weightlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
