# Generated by Django 2.0.5 on 2018-07-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180721_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='weight_history',
        ),
        migrations.DeleteModel(
            name='WeightList',
        ),
    ]
