# Generated by Django 2.0.5 on 2018-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180721_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='weight_history',
            field=models.ManyToManyField(blank=True, related_name='weight_list', to='accounts.WeightList'),
        ),
    ]
