# Generated by Django 2.0.5 on 2018-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_weightlist_body_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
