# Generated by Django 2.0.5 on 2018-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180728_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlist',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
