# Generated by Django 2.0.5 on 2018-08-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180728_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightlist',
            options={'ordering': ['timestamp']},
        ),
    ]
