# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['creation_date']},
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='creation date',
            new_name='creation_date',
        ),
    ]
