# Generated by Django 2.0.7 on 2018-09-01 13:56

from django.db import migrations, models
import workout.models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='creation_date',
            field=models.DateField(help_text='Enter date', validators=[workout.models.no_future]),
        ),
    ]
