# Generated by Django 2.0.7 on 2018-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20180915_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='1', max_length=20),
        ),
    ]
