# Generated by Django 2.0.7 on 2018-09-07 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nutrition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('energy', models.FloatField()),
            ],
            options={
                'ordering': ['time'],
                'get_latest_by': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=40, unique=True)),
                ('date', models.DateField(help_text='Enter date', validators=[nutrition.models.no_future])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='nutrition',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.Plan'),
        ),
    ]
