# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='energy',
            field=models.IntegerField(),
        ),
    ]
