# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180804_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='energy',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
