# Generated by Django 2.0.7 on 2018-09-12 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0002_auto_20180912_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('subtitle', 'user')},
        ),
    ]
