# Generated by Django 2.0.7 on 2018-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20180912_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='subtitle',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
    ]
