# Generated by Django 2.0.7 on 2018-09-01 13:56

import appointments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_remove_appointment_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(help_text='Enter date', validators=[appointments.models.no_future]),
        ),
    ]
