# Generated by Django 2.0.7 on 2018-09-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20180901_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sender',
        ),
    ]
