# Generated by Django 2.0.5 on 2018-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
