# Generated by Django 2.0.7 on 2018-08-23 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
    ]
