# Generated by Django 2.0.7 on 2018-08-23 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_auto_20180823_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
        migrations.RenameModel(
            old_name='Chat',
            new_name='Thread',
        ),
    ]
